SEED = 0
KBIT = 1024 / 8
MBIT = 1024 * KBIT

N_USERS = 100
USER_UPLINK = 0.1 * MBIT
USER_DOWNLINK = 1 * MBIT
TX_RATE = 10.  # tx/s, globally
N_USER_CONNECTIONS = 5

COLLATOR_UPLINK = 10 * MBIT
COLLATOR_DOWNLINK = 1 * MBIT
N_COLLATOR_CONNECTIONS = 100
COLLATION_INTERVAL = 5  # s

N_KEYPERS = 10
KEYPER_THRESHOLD = 7
KEYPER_UPLINK = 0.1 * MBIT
KEYPER_DOWNLINK = 1 * MBIT
N_KEYPER_CONNECTIONS = 5
